steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'asia-southeast2-docker.pkg.dev/$PROJECT_ID/recommender-api/recommender-api:$COMMIT_SHA',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'asia-southeast2-docker.pkg.dev/$PROJECT_ID/recommender-api/recommender-api:$COMMIT_SHA',
      ]
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'hayuk-recommender-api', '--image', 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/recommender-api/recommender-api:$COMMIT_SHA', '--allow-unauthenticated', '--service-account', 'hayuk-recommender-api@hayuk-project.iam.gserviceaccount.com', '--region', 'asia-southeast2', '--cpu', '1,' '--memory', '0', '--min-instances', '0', '--max-instances', '1', '--set-env-vars', '[PROJECT_ID=$PROJECT_ID, ACCESS_TOKEN=$$TOKEN, ENDPOINT_ID=$$ENDPOINT, DB_HOST=$$HOST, DB_PASS=$$PASS]']
    secretEnv: ['TOKEN', 'ENDPOINT', 'HOST', 'PASS']
options:
  logging: CLOUD_LOGGING_ONLY
images:
  - 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/recommender-api/recommender-api:$COMMIT_SHA'
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/hayuk-recommender-api-secrets/versions/latest
      env: 'TOKEN'
    - versionName: projects/$PROJECT_ID/secrets/hayuk-recommender-api-endpoint-id/versions/latest
      env: 'ENDPOINT'
    - versionName: projects/$PROJECT_ID/secrets/hayuk-recommender-api-db-host/versions/latest
      env: 'HOST'
    - versionName: projects/$PROJECT_ID/secrets/hayuk-recommender-api-db-pass/versions/latest
      env: 'PASS'
